version: '3'

services:
  zoo-app:
    container_name: zoo-app
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PACT_BROKER_BASE_URL: "http://pact-broker:9292"
    volumes:
      - .:/app
      - zoo-app-bundle-cache:/usr/local/bundle